[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions/"

# This rule handles the root URL for instructions
[[redirects]]
  from = "/"
  to = "/.netlify/functions/rating"
  status = 200

# This is the CRUCIAL rule for the URL you are using.
# It captures any path like "/kandari_arjun"
[[redirects]]
  from = "/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200