[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/user/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200

[[redirects]]
  from = "/api/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200
