[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."rating"]
  runtime = "python3.11"

[[redirects]]
  from = "/user/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200

[[redirects]]
  from = "/api/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200
