[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."rating"]
  runtime = "python3.8"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/rating"
  status = 200

[[redirects]]
  from = "/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200
