[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/user/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200

[[redirects]]
  from = "/api/:username"
  to = "/.netlify/functions/rating?username=:username"
  status = 200
